# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_base_joint:
    has_velocity_limits: true
    max_velocity: 0.72
    has_acceleration_limits: false
    max_acceleration: 0
  arm_first_joint:
    has_velocity_limits: true
    max_velocity: 2.63
    has_acceleration_limits: false
    max_acceleration: 0
  arm_second_joint:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: false
    max_acceleration: 0
  hand_joint:
    has_velocity_limits: true
    max_velocity: 0.78539816339
    has_acceleration_limits: false
    max_acceleration: 0
  tower_joint:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: false
    max_acceleration: 0